export const COUNTRIES_LOADING = "COUNTRIES_LOADING";
export const COUNTRIES_FAILED = "COUNTRIES_FAILED";
export const COUNTRIES_SUCCESS = "COUNTRIES_SUCCESS";

export const COUNTRY_LOADING = "COUNTRY_LOADING";
export const COUNTRY_FAILED = "COUNTRY_FAILED";
export const COUNTRY_SUCCESS = "COUNTRY_SUCCESS";

export const CHANGE_THEME = "CHANGE_THEME";

export const SET_FILTER = "SET_FILTER";
